
import java.awt.Image;
import java.awt.Toolkit;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Rolivis
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    Registro registro = new Registro("registro", "registro123", "registro");

    public Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        llenarchoices();
    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/bayern.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jf_inicioregistro = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ch_clases_registro = new java.awt.Choice();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jl_claveregistro = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jl_usuarioregistro = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jl_correoregistro = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        ch_maestros_registro = new java.awt.Choice();
        ch_alumnos_registro = new java.awt.Choice();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_user = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pf_clave = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jl_fondo = new javax.swing.JLabel();

        jf_inicioregistro.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jf_inicioregistro.setTitle("Regsitro FCB UNITEC");
        jf_inicioregistro.setIconImage(getIconImage());
        jf_inicioregistro.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jf_inicioregistro.setSize(new java.awt.Dimension(1920, 1080));
        jf_inicioregistro.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(193, 216, 252));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Bayern superchiquito.png"))); // NOI18N
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 10, 50, 60));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Bayern superchiquito.png"))); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 50, 60));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("BIEVENIDO A REGISTRO");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 6, 870, 70));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo rojo mejor.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2000, 85));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2003, 12, -1, -1));

        ch_clases_registro.setBackground(new java.awt.Color(193, 216, 252));
        ch_clases_registro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ch_clases_registro.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        ch_clases_registro.setForeground(new java.awt.Color(0, 0, 0));
        ch_clases_registro.setName(""); // NOI18N
        ch_clases_registro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ch_clases_registroItemStateChanged(evt);
            }
        });
        jPanel1.add(ch_clases_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 150, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 140, 330));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Administrar Maestros");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 190, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 204, 204));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Administrar Clases");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 190, 20));

        jl_claveregistro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jl_claveregistro.setForeground(new java.awt.Color(255, 255, 255));
        jl_claveregistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_claveregistro.setText("***********");
        jPanel1.add(jl_claveregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 910, 190, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Opciones de");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 110, 20));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Contraseña");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 880, 110, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Usuario");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 730, 110, 20));

        jl_usuarioregistro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jl_usuarioregistro.setForeground(new java.awt.Color(255, 255, 255));
        jl_usuarioregistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_usuarioregistro.setText("registro");
        jPanel1.add(jl_usuarioregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 760, 180, 20));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Correo");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 800, 100, 20));

        jl_correoregistro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jl_correoregistro.setForeground(new java.awt.Color(255, 255, 255));
        jl_correoregistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_correoregistro.setText("registro@unitec.edu.fcb");
        jPanel1.add(jl_correoregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 830, 190, 20));

        jButton3.setBackground(new java.awt.Color(193, 216, 252));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Cerrar Sesion");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 950, 130, 50));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("registro");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 110, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Informacion");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 690, 110, 20));

        ch_maestros_registro.setBackground(new java.awt.Color(193, 216, 252));
        ch_maestros_registro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ch_maestros_registro.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        ch_maestros_registro.setName(""); // NOI18N
        ch_maestros_registro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ch_maestros_registroItemStateChanged(evt);
            }
        });
        jPanel1.add(ch_maestros_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 150, -1));

        ch_alumnos_registro.setBackground(new java.awt.Color(193, 216, 252));
        ch_alumnos_registro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ch_alumnos_registro.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        ch_alumnos_registro.setForeground(new java.awt.Color(0, 0, 0));
        ch_alumnos_registro.setName(""); // NOI18N
        ch_alumnos_registro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ch_alumnos_registroItemStateChanged(evt);
            }
        });
        jPanel1.add(ch_alumnos_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 150, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 204, 204));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Administrar Alumnos");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 190, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo rojo mejor.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 1050));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Usted administra toda esta plataforma");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, 460, 60));

        jScrollPane1.setBackground(new java.awt.Color(179, 205, 252));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(142, 182, 252));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("\t\t                  ¡¡MUCHAS GRACIAS POR ACEPTAR ESTE TRABAJO!!\n\n Confiamos en ti y dejamos la plataforma a tus manos para que no haya ni tan solo un error y que pueda funcionar perfectamente para\n    que nuestros alumnos puedan tener la mejor experiencia posible a la hora de utilizar nuestro programa con sus caracteristicas que \n se han estado programando por mas de 4 semanas y que de requisitos estaba el esforzarse demasiado y meterle mucho amor y animo.");
        jTextArea1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 520, 920, 120));

        jScrollPane2.setBackground(new java.awt.Color(179, 205, 252));

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(142, 182, 252));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("\t\n\tUsted es registro y no hay nadie que pueda hacer todo lo que usted hace, Aqui se podra crear lo que\t\t\n usted quiere ya que en este sistema encontramos maestros, alumos y tambien clases que cursaran los mismos alumnos por los maestros.\n\n   Aqui se podra ingresar, modificar y expulsar lo que viene ser los alumnos y los maestros. Tambien estara encargado de administrar las \nclases dadas por los maestros y las clases cursadas por los alumnos ya que debera matricularlos en el apartado de \"Administrar alumnos\".\n\n Usted al ser el usuario de registro tiene el privilegio de poder cerrar sesion y tambien cerrar el sistema completamente por si hay un fallo\n\t                  que arreglar o administrar con nuestros Ingenieros en Sistemas Computacionales.");
        jTextArea2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 960, 210));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setText("UNITEC FCB © 2023 | Derechos reservados.");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 950, 350, 60));

        jf_inicioregistro.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1960, 1050));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FCB UNITEC");
        setIconImage(getIconImage());
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BIENVENIDO A FCB UNITEC");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 690, 120));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Bayern chiqui.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 280, 150, 170));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contraseña de Usuario:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 700, -1, 40));

        tf_user.setBackground(new java.awt.Color(242, 242, 242));
        tf_user.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(tf_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 620, 440, 40));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre de Usuario:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 620, 210, 40));

        pf_clave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(pf_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 700, 440, 40));

        jButton1.setText("ENTRAR");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 790, 180, 60));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Iniciar Sesion");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 520, 230, 50));

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 740, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Registro");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1800, 900, 70, -1));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Contraseña:");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1760, 960, 70, -1));

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("registro");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1830, 930, 50, -1));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("registro123");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1830, 960, 80, -1));

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Usuario:");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(1780, 930, 50, -1));

        jl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo rojo mejor.png"))); // NOI18N
        getContentPane().add(jl_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1050));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String clave = new String(pf_clave.getPassword());
        if (tf_user.getText().equals("registro") && clave.equals("registro123")) {
            jf_inicioregistro.setLocationRelativeTo(this);
            jf_inicioregistro.setExtendedState(MAXIMIZED_BOTH);
            jf_inicioregistro.setVisible(true);
            this.setVisible(false);
            tf_user.setText("");
            pf_clave.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jf_inicioregistro.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ch_maestros_registroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ch_maestros_registroItemStateChanged

    }//GEN-LAST:event_ch_maestros_registroItemStateChanged

    private void ch_clases_registroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ch_clases_registroItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ch_clases_registroItemStateChanged

    private void ch_alumnos_registroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ch_alumnos_registroItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ch_alumnos_registroItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice ch_alumnos_registro;
    private java.awt.Choice ch_clases_registro;
    private java.awt.Choice ch_maestros_registro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JFrame jf_inicioregistro;
    private javax.swing.JLabel jl_claveregistro;
    private javax.swing.JLabel jl_correoregistro;
    private javax.swing.JLabel jl_fondo;
    private javax.swing.JLabel jl_usuarioregistro;
    private javax.swing.JPasswordField pf_clave;
    private javax.swing.JTextField tf_user;
    // End of variables declaration//GEN-END:variables

    private void llenarchoices() {

        ch_maestros_registro.add("Ingresar Maestro");
        ch_maestros_registro.add("Modificar Maestro");
        ch_maestros_registro.add("Eliminar Maestro");
        ch_maestros_registro.add("<Vacio>");
        ch_maestros_registro.select(3);

        ch_alumnos_registro.add("Ingresar Alumno");
        ch_alumnos_registro.add("Modificar Alumno");
        ch_alumnos_registro.add("Eliminar Alumno");
        ch_alumnos_registro.add("<Vacio>");
        ch_alumnos_registro.select(3);

        ch_clases_registro.add("Ingresar Clase");
        ch_clases_registro.add("Modificar Clase");
        ch_clases_registro.add("Eliminar Clase");
        ch_clases_registro.add("<Vacio>");
        ch_clases_registro.select(3);
    }

}
